spring:
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
server:
  port: 8761

# CONFIGURAÇÕES EUREKA
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    registerWithEureka: false
    fetchRegistry: false
    healthcheck: enabled
    serviceUrl:
      defaultZone: ${EUREKA_PROTOCOL}://${EUREKA_URL}/eureka/
  instance:
    hostname: ${EUREKA_URL}

# CONFIGURAÇÕES ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    gateway:
      enabled:
        true