server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck: enabled
    serviceUrl:
    defaultZone: http://${DISCOVERY_SERVICE_IP}:8761/eureka/
  instance:
    hostname: ${DISCOVERY_SERVICE_IP:127.0.0.1}

